# Generated by Django 3.2.8 on 2021-10-09 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, verbose_name='Краткое описание')),
                ('from_location', models.CharField(db_index=True, max_length=255, verbose_name='От куда')),
                ('to_location', models.CharField(db_index=True, max_length=255, verbose_name='До куда')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('choices_types', models.CharField(choices=[('WALK', 'Пешком'), ('BUS', 'На автобусе'), ('TAXI', 'На такси'), ('CAR', 'На машине')], default='CAR', max_length=4, verbose_name='Выбор поездки')),
                ('days_on_week', models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], default='1', max_length=7, verbose_name='Дни недель')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Дата когда будет идти маршрут')),
                ('date_time_end', models.DateTimeField(auto_now=True, verbose_name='Дата когда закончиться маршрут')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Описание пути')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='Main.mapsmodel', verbose_name='Карта пути')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_maps', to=settings.AUTH_USER_MODEL, verbose_name='Пользоваеть')),
            ],
        ),
    ]
