release: pip install -r requirements.txt --no-input
release: heroku config:set DISABLE_COLLECTSTATIC=1 --no-input
release: python3 manage.py makemigrations --no-input
release: python3 manage.py migrate --no-input

web: Sharit.wsgi